VERSION = "3.1.0"
DEFAULT_MAX_ITERATIONS = 20
DEFAULT_COMPLETION_PROMISE = "DONE"
DEFAULT_TIMEOUT_SECONDS = 3600
DEFAULT_SESSION_TIMEOUT = 0
TERMINATION_GRACE_SECONDS = 10
MAX_OUTPUT_BYTES = 1024 * 1024
